name: arasu
version: 0.1.1
author: Thaniyarasu Kannusamy <thaniyarasu@gmail.com>
description: Arasu package to manage arasu apps
homepage: http://arasuframework.org
dependencies:
  angular: ">=0.12.0 <0.13.0"
  logging: ">=0.9.2 <0.10.0"
  unittest: ">=0.11.0+3 <0.12.0"

