name: arasu
version: 0.1.3
author: Thaniyarasu Kannusamy <thaniyarasu@gmail.com>
description: Arasu package to manage arasu apps
homepage: http://arasuframework.org
dependencies:
  angular2: any
  logging: any
  test: any
